export const SET_DOCTORS_LOADING = "SET_DOCTORS_LOADING";
export const SET_DOCTORS_SUCCESS = "SET_DOCTORS_SUCCESS";
export const SET_DOCTORS_ERROR = "SET_DOCTORS_ERROR";

export const SET_DOCTOR_CREATE_LOADING = "SET_DOCTOR_CREATE_LOADING";
export const SET_DOCTOR_CREATE_SUCCESS = "SET_DOCTOR_CREATE_SUCCESS";
export const SET_DOCTOR_CREATE_ERROR = "SET_DOCTOR_CREATE_ERROR";

export const SET_DOCTOR_DELETE_LOADING = "SET_DOCTOR_DELETE_LOADING";
export const SET_DOCTOR_DELETE_SUCCESS = "SET_DOCTOR_DELETE_SUCCESS";
export const SET_DOCTOR_DELETE_ERROR = "SET_DOCTOR_DELETE_ERROR";

export const SET_DOCTOR_UPDATE_LOADING = "SET_DOCTOR_UPDATE_LOADING";
export const SET_DOCTOR_UPDATE_SUCCESS = "SET_DOCTOR_UPDATE_SUCCESS";
export const SET_DOCTOR_UPDATE_ERROR = "SET_DOCTOR_UPDATE_ERROR";
