export const SET_SINGLE_DOCTOR_ERROR = "SET_SINGLE_DOCTOR_ERROR";
export const SET_SINGLE_DOCTOR_LOADING = "SET_SINGLE_DOCTOR_LOADING";
export const SET_SINGLE_DOCTOR_SUCCESS = "SET_SINGLE_DOCTOR_SUCCESS";
